name: jenkins-operator
namespace: ""
platform: "openshift"
image:
  name: epamedp/jenkins-operator
  version: v2.4.0

edp:
  name: "stub-edp-name"
  dnsWildCard: "delivery.aws.main.edp.projects.epam.com"

jenkins:
  deploy: true
  initImage: "busybox"
  image: "epamedp/edp-jenkins"
  version: "2.4.0"
  storageClass: gp2
  volumeCapacity: 10Gi
  libraryPipelinesRepo: "https://github.com/epmd-edp/edp-library-pipelines.git"
  libraryPipelinesVersion: "master"
  libraryStagesRepo: "https://github.com/epmd-edp/edp-library-stages.git"
  libraryStagesVersion: "master"
  pullSecrets:
  basePath: