apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jenkins.storage.size }}
  storageClassName: {{ .Values.jenkins.storage.class }}
  volumeMode: Filesystem